version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "America/Bogota"
    labels:
      - "dependencies"
      - "maven"
    assignees:
      - "aguirre-jes"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "America/Bogota"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "aguirre-jes"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "America/Bogota"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "aguirre-jes"
    groups:
      actions:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"