name: Container Build & Security Scan
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  verify-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.4.3'
      - name: Verify Distroless Base Image Signature
        run: |
          IMAGE_NAME="gcr.io/distroless/java-base-debian12:latest"
          cosign verify $IMAGE_NAME --certificate-oidc-issuer https://accounts.google.com --certificate-identity keyless@distroless.iam.gserviceaccount.com
  build-and-push:
    needs: verify-base-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN_PAYMENT_API }}
      - name: Build and push image container to GitHub Container Registry
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64
          file: Dockerfile.jlink
          cache-from: type=gha
          cache-to: type=gha,mode=max
  scan-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
