name: Java Tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Dockerfile*'
      - 'pom.xml'
    branches: [ master ]
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
          fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar -Dsonar.projectKey=aguirre-jes_payments-api

