name: Java Tests
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'Dockerfile*'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Dockerfile*'
      - 'pom.xml'
    branches: [ master ]
jobs:
  run-tests:
    name: Run Tests with TestContainers
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn test
