name: Tests Java
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Dockerfile*'
      - 'pom.xml'
    branches: [ master ]
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn -B test
